# Predicting the CO2 Emissions from a Vehicle using Machine Learning

The Framework I will be following:

1. Problem Definition
2. Data
3. Evaluation
4. Features
5. Modelling
6. Experimentation

## 1. Problem Definition

> The goal is to predict the CO2 Emissions from a Vehicle using Scikit-Learn's Regression Models, given information on vehicle specifications, fuel consumption and labelled CO2 emmisions.

## 2. Data
The data is downloaded from Kaggle - https://www.kaggle.com/datasets/brsahan/vehicle-co2-emissions-dataset?resource=download

## 3. Evaluation

> The goal for this project is to build a Machine Learning model which minimizes the R^2 (R-squared value /  coefficient of determination) as well as evaluating on other metrics too.

## 4. Features
**Data Dictionary**

1. Make: Vehicle brand or manufacturer
2. Model: Specific model of vehicle
3. Vehicle Class: Class of vehicle depending on their utility, capacity and weight
4. Engine Size (L): Engine size in litres
5. Cylinders: Number of cylinders in the engine
6. Transmission: Transmission type with number of gears
    * A = Automatic
    * AM = Automated manual
    * AS = Automatic with select shift
    * AV = Continuously variable
    * M = Manual
    * 3 - 10 = Number of gears

7. Fuel Type: Type of Fuel used
    * X = Regular gasoline
    * Z = Premium gasoline
    * D = Diesel
    * E = Ethanol (E85)
    * N = Natural gas

8. Fuel Consumption City (L/100 km): Fuel consumption in city roads (L / 100 KM)
9. Fuel Consumption Hwy (L/100 km): Fuel consumption in highways (L / 100 KM)
10. Fuel Consumption Comb (L/100 km): Combined city and highway Fuel consumption (L / 100 KM)
11. Fuel Consumption Comb (mpg): Combined city and highway Fuel consumption in miles per galon (mpg)
12. CO2 Emissions(g/km): The tailpipe emissions of carbon dioxide (in grams per kilometre) for combined city and highway driving

In [1]:
# Importing tools
import numpy as mp
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

In [2]:
df = pd.read_csv("co2.csv")
df.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [3]:
df.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [5]:
df.shape

(7385, 12)

In [6]:
df.isna().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [9]:
df["Vehicle Class"].value_counts()

Vehicle Class
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: count, dtype: int64

In [10]:
df["Make"].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

In [12]:
df["Model"].value_counts()

Model
F-150 FFV                                 32
F-150 FFV 4X4                             32
MUSTANG                                   27
FOCUS FFV                                 24
SONIC                                     20
                                          ..
Highlander Hybrid AWD Limited/Platinum     1
RAV4 AWD TRD Off-Road                      1
Tacoma 4WD D-Cab TRD Off-Road/Pro          1
Atlas Cross Sport 4MOTION                  1
XC40 T4 AWD                                1
Name: count, Length: 2053, dtype: int64

In [13]:
df["Transmission"].value_counts()

Transmission
AS6     1324
AS8     1211
M6       901
A6       789
A8       490
AM7      445
A9       339
AS7      319
AV       295
M5       193
AS10     168
AM6      132
AV7      118
AV6      113
M7        91
A5        84
AS9       77
A4        65
AM8       62
A7        53
AV8       39
A10       31
AS5       26
AV10      11
AM5        4
AM9        3
AS4        2
Name: count, dtype: int64

In [14]:
df["Fuel Type"].value_counts()

Fuel Type
X    3637
Z    3202
E     370
D     175
N       1
Name: count, dtype: int64